### ISSUE TITLE
__main__.py: error: argument -dlall/--downloadall: expected one argument

### ISSUE THREAD

**Issue by mhep** [johnludwigm/Radiolab#1]
First off, thanks for putting this together! 

I'm running into an issue when using this on macOS. If I attempt to download all episodes, 

`python3 -m radiolab -dlall -dest /Users/user/Downloads/radiolab`

I get the following error: 

`__main__.py: error: argument -dlall/--downloadall: expected one argument`

Any idea what I may be doing wrong? Thanks!

**Comment by johnludwigm** [comment]
I'll look at this later tonight. Thank you!


Edit:

The argument parser needs to take `-dlall` or `--downloadall` as a boolean (present or not). If you want to try to fix it yourself and submit a pull request, then I can certainly accommodate that.


Otherwise, I'll get to it sometime this weekend to make the update (and likely update the episode catalog too!).


Edit 2:

I will get to this one day and will let you know when I have fixed the issue.
